### ISSUE TITLE
FEAT: 회원가입 및 로그인 API 및 테스트 코드 작성 

### ISSUE THREAD

**Issue by JaeHyuckSa** [sideProject21/BE_REPO#1]
##  이슈 내용
> 이슈 내용 작성
>
- [API 명세서](https://battle-tsunami-580.notion.site/7d57896248024ae68e51d969e04400b3?v=fa3c77ffa17f43e2a2afe96640c752ad&pvs=4)

|기능|Method|URL|Request|Response|
|------|---|---|---|---|
|로그인|POST|/api/v1/auth/signin|username, password|accessToken, refreshToken|
|인증토큰 재발급|POST|/api/v1/auth/jwt/refresh|refreshToken|accessToken|
|회원가입 |POST|/api/v1/auth/signup|username,nickname, password, userRole, verificationCode|id, username, nickname, userRole|
|아이디 및 인증코드 검증|POST|/api/v1/auth/validate|validateValue, validateType|validateType, isValid|

<br>

##  작업 사항
- [x] 로그인 API 및 관련 테스트 코드 작성 
- [x] 인증토큰 재발급 API 및 관련 테스트 코드 작성 
- [x] 회원가입 API 및 관련 테스트 코드 작성 
- [x] 아이디 및 인증코드 검증 API 및 관련 테스트 코드 작성 

<br>

##  관련 이슈
- x

<br>

## 기타사항
- x

<br>

**Comment by saJaeHyukc** [comment]
급한 기능 추가를 위해 테스트 누락...
테스트 추가 후 이슈 Close
