### ISSUE TITLE
DOCS: 프로젝트 ERD 작성

### ISSUE THREAD

**Issue by JaeHyuckSa** [sideProject21/BE_REPO#2]
##  이슈 내용
> 이슈 내용 작성
>
아래는 프로젝트의 ERD(데이터베이스 구조)를 단계별로 작성하는 이슈입니다.

[ERD 링크](https://www.erdcloud.com/d/7GkitftZxfXGDthrv)
<br>

##  작업 사항
- [x] 유저 ERD 작성
- [ ] - 작성 예정 - 

<br>

##  관련 이슈
- #x

<br>

## 기타사항
x 

<br>

**Comment by saJaeHyukc** [comment]
<img width="947" alt="스크린샷 2024-01-08 오전 12 28 23" src="https://github.com/sideProject21/BE_REPO/assets/104830931/17ef3ae1-d1c3-4357-8af5-bc75fdbc6bcf">
